# Generated by Django 4.1.7 on 2023-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='english',
            new_name='original',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='russian',
            new_name='translate',
        ),
    ]
